### PR TITLE
Update Gradle plugin to 2.1.2

### PR DESCRIPTION
**Pull request by danybony**
As title says, update to stable version

### CODE REVIEW

**Comment by ouchadam** [comment]
E Z P Z :+1:

**Comment by frapontillo** [comment]
It's always hard trusting Gradle to "just work". PRB? 😄

**Comment by ouchadam** [comment]
I've got faith

**Comment by danybony** [comment]
It wasn't even building on master with the new CI settings, the PRB couldn't have started in the first place 👅

**Comment by frapontillo** [comment]
...or not @ouchadam

**Pull request merged**
